name: Update Badges

on:
  schedule:
    - cron: "0 2 * * *"
  workflow_dispatch:

jobs:
  update-badges:
    name: Update README with Credly badges
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Update badges
        uses: pemtajo/badge-readme@v3.2
        with:
          CREDLY_USER: han-li.e090ae07
          NUMBER_LAST_BADGES: 0
